### ISSUE TITLE
ลงสคริป Scotty ดึงมาจากเซิฟเก่าได้เลย

### ISSUE THREAD

**Issue by ARGONG** [Mail3ee/Sneaker#24]
- Battle X
- Online Reward
- Gachapon
- Casino: Pok Deng
- Crafting Table
- Extended Job

* เอาจากเซิฟเก่ามาได้เลยจ้าา

**Comment by Mail3ee** [comment]
ต้องลงตัวใหม่ล่าสุดและเซ็ทใหม่ทั้งหมด
