### ISSUE TITLE
เพิ่มของที่จะให้มีในร้านขายของทั่วไป

### ISSUE THREAD

**Issue by ARGONG** [Mail3ee/Sneaker#28]
* ของที่จะให้มีในร้านขาย

- โทรศัพท์ 1,500
- กล่อส่องทางไกล 5,000
- วิทยุ 10000
- หนังสือโอนรถ  30,000
- ผ้าเช็ดรถ 250
- ดอกกุหลาบ 120
- เบียร์ 200

- แฮมเบอร์เกอร์  35
- ข้าวกระเพราะหมู 70
- ข้าวแกงกระหรี่ 150

- น้ำเปล่า 25
- โอเลี้ยงยกล้อ 50 
-  ชามะนาว  100

**Comment by Mail3ee** [comment]
ดอกกุหลาบไม่มีนะครับ
